version: "2.3"
services:
  kinetica:
    image: kinetica/kinetica-intel
    ports:
      - "8080:8080"  # Admin
      - "8088:8088"  # Reveal
      - "9191:9191"  # REST API
    privileged: true
    mem_limit: 8g
  python:
    build:
      context: .
      dockerfile: docker/python.dockerfile