version: "2.3"
services:
  kinetica:
    environment:
      - LICENSE_KEY=YC3dbsSeT2wm-bUYeHl+eGB0l-79+nU+JwTZNA-xSgcqXAZxRAU-Y24mK/UykRmFtBTV7Sl1lwlDj0oq6lpw
    build:
      context: docker/
      dockerfile: kinetica.dockerfile
    ports:
      - "8080:8080"  # Admin
      - "8088:8088"  # Reveal
      - "9191:9191"  # REST API
    privileged: true
    mem_limit: 4g
    restart: on-failure
  python:
    build:
      context: .
      dockerfile: docker/python.dockerfile
    depends_on:
      - kinetica
    restart: on-failure
