version: "2.3"
services:
  kinetica:
    environment:
      - LICENSE_KEY=
    build:
      context: kinetica-backend/docker
      dockerfile: kinetica.dockerfile
    ports:
      - "8080:8080"  # Admin
      - "8088:8088"  # Reveal
      - "9191:9191"  # REST API
    privileged: true
    mem_limit: 8g
    restart: on-failure
  python:
    build:
      context: kinetica-backend/python-backend
      dockerfile: python.dockerfile
    depends_on:
      - kinetica
    restart: on-failure


